// Flower IDs start from 1 and are monotonically increasing.
// Each flower has an image named after its ID.
export const FLOWERS = Object.freeze([
  '',
  'Black Cosmos',
  'Orange Cosmos',
  'Pink Cosmos',
  'Red Cosmos',
  'White Cosmos',
  'Yellow Cosmos',
  'Blue Hyacinth',
  'Orange Hyacinth',
  'Pink Hyacinth',
  'Purple Hyacinth',
  'Red Hyacinth',
  'White Hyacinth',
  'Yellow Hyacinth',
  'Black Lily',
  'Orange Lily',
  'Pink Lily',
  'Red Lily',
  'White Lily',
  'Yellow Lily',
  'Green Mum',
  'Pink Mum',
  'Purple Mum',
  'Red Mum',
  'White Mum',
  'Yellow Mum',
  'Blue Pansy',
  'Purple Pansy',
  'Red Pansy',
  'Orange Pansy',
  'White Pansy',
  'Yellow Pansy',
  'Black Rose',
  'Blue Rose',
  'Gold Rose',
  'Orange Rose',
  'Pink Rose',
  'Purple Rose',
  'Red Rose',
  'White Rose',
  'Yellow Rose',
  'Black Tulip',
  'Orange Tulip',
  'Pink Tulip',
  'Purple Tulip',
  'Red Tulip',
  'White Tulip',
  'Yellow Tulip',
  'Blue Windflower',
  'Orange Windflower',
  'Pink Windflower',
  'Purple Windflower',
  'Red Windflower',
  'White Windflower',
  'Lily of the Valley',
]);

export const DEFAULT_DIMENSIONS = Object.freeze({ width: 30, height: 30 });
